### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kztyes** [morispi/LEVIATHAN#2]
After this error, the instruction stopped running. Why？
My bam:   Hg002_NA24385  
My Ref:     hg19
![微信图片_20210425100741](https://user-images.githubusercontent.com/55338332/115977862-52625280-a5ae-11eb-911c-f8ce5dcc1e9c.png)

**Comment by morispi** [comment]
Hello,

Segmentation faults are always pretty hard to understand / reproduce without the original data unfortunately.
If your dataset is publicly available, could you send my its accession number or a link so I can download it and try to see what's going on?

If not, could you maybe do a `samtools view yourBamFile.bam | head` so I can try to see if there something wrong with the way your input file is formatted?

Best,
Pierre

**Comment by kztyes** [comment]
Thank you for your quick reply. The data I used is long_read_based, i don't really know if i can use Levithan to detect structural variation. And this is the header of the BAM file I used:

[hg002_allreads_ngmlr.2.txt](https://github.com/morispi/LEVIATHAN/files/6376613/hg002_allreads_ngmlr.2.txt)

**Comment by morispi** [comment]
Oh, if your data is long reads (PacBio, ONT), there is a large chance LEVIATHAN will not manage to perform, indeed. LEVIATHAN has been designed to call SVs on Linked-Reads data, such as 10x Genomics, stLFR, Haplotagging or TELL-Seq. If your reads are not barcoded, there is a huge chance LEVIATHAN will fail to work, indeed.

Sorry if I have not been clear enough, but I would also need some alignments data to better understand what's wrong, and not only the headers. Could you possibly send me another file including some alignments?

Best,
Pierre
