### ISSUE TITLE
overflow error

### ISSUE THREAD

**Issue by dipopp** [morispi/LEVIATHAN#3]
During bench marking with the Genome in a Bottle datasets, the program crashed immediately after creating the candidates.bedpe.
I ran:
`LEVIATHAN -b LongRanger/GIAB/outs/possorted_bam.bam -i barcodeIndex.bci -g GRCh37_longranger/refdata-hg19-2.1.0/fasta/genome.fa -o GIAB_Leviathan.vcf -t 12`

The error is:
`terminate called after throwing an instance of 'std::overflow_error'
  what():  robin_hood::map overflow`

**Comment by flegeai** [comment]
Hi dipopp,
Thanks for reporting this issue. We were able to reproduce it, and then correct it (a hash table was not purged and kept to much memory). I hope this new version will work on your data.
Best regards,
