### ISSUE TITLE
Handling missing haplotag barcodes

### ISSUE THREAD

**Issue by pdimens** [morispi/LEVIATHAN#8]
Does Leviathan have a routine/process to identify when there is an invalid/missing haplotagging barcode such that it does not consider the BX tag valid?

For example, an invalid haplotagging BX barcode would have `00` in any of the 4 positions, e.g. `A00C41B11D94`, `A00C03B57D00`, etc. Does LRez/Leviathan recognize that these are invalid and should not be considered when clustering alignments by presumed BX molecule?

**Comment by clemaitre** [comment]
Hi,

Yes, LRez checks the validity of all barcodes (see source code [here](https://github.com/morispi/LRez/blob/c9b378c53d81cf7cc28516eeefe2045b02583ecc/src/utils.cpp#L72)) and indexes only the valid ones. As Leviathan is based on LRez indexes, it has the same behaviour : invalid barcodes are excluded from the analyses.
In case of Haplotagging data, a barcode with `00` in any of the 4 positions is considered as invalid.

Best,
Claire

**Comment by pdimens** [comment]
Thank you very much for the clarification and explanation, Claire!

Best,
Pavel
